spring:
    application:
        name: api
    datasource:
        url: ${DATABASE_URL:jdbc:postgres://localhost:5432/tweet-db}
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    flyway:
        enabled: true
        baseline-on-migrate: true

server:
    port: ${SERVER_PORT:8080}
    